#!/bin/csh -f

#set key = "東森新聞 51 頻道 24 小時直播"


foreach key ("`cat ./channel`")

  set id = `yt-dlp "ytsearch:$key  --get-id`

  echo $id
  
  echo "東森新聞,https://www.youtube.com/watch?v="$id > yturl

end
